name = "storied"
compatibility_date = "2026-04-16"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "storied-db"
database_id = "546b0f58-ca90-415a-9968-f05d52925e1a"
migrations_dir = "migrations"

[vars]
SEND_EMAILS = ""
FILE_BASE_URL = "https://assets.bermudatrianglesociety.com"
ALLOW_SIGNUP = "no"

[[r2_buckets]]
binding = "FILES"
bucket_name = "storied"

[[routes]]
pattern = "discuss.bermudatrianglesociety.com"
custom_domain = true

[[queues.producers]]
binding = "WORKER_QUEUE"
queue = "storied-worker-tasks"

[[send_email]]
name = "EMAIL"
allowed_sender_addresses = ["notify@discuss.bermudatrianglesociety.com"]
