-- Migration number: 0004    (timestamp auto)
-- Seed genres table
INSERT INTO genres (id, name, slug, parent_id, description, is_speculative) VALUES
  (1, 'Science Fiction', 'science-fiction', NULL, 'Speculation driven by science, engineering, space, time, and the consequences of technology.', 1),
  (2, 'Hard SF', 'hard-sf', 1, 'Sticks closely to known science/engineering and extrapolates carefully.', 1),
  (3, 'Engineering SF', 'engineering-sf', 2, 'Plots hinge on building, fixing, or optimizing complex technical systems.', 1),
  (4, 'Scientific Problem-Solving SF', 'scientific-problem-solving-sf', 2, 'Characters tackle puzzles grounded in physics, biology, or math.', 1),
  (5, 'Soft SF', 'soft-sf', 1, 'Focuses more on psychology, sociology, anthropology, and culture than equations.', 1),
  (6, 'Social SF', 'social-sf', 5, 'Examines how societies change under new conditions or inventions.', 1),
  (7, 'Anthropological SF', 'anthropological-sf', 5, 'Uses alien cultures or future peoples to explore human assumptions.', 1),
  (8, 'Space Opera', 'space-opera', 1, 'Big-emotion, big-scale adventures across star systems with politics and war.', 1),
  (9, 'Military Space Opera', 'military-space-opera', 8, 'Fleet tactics, campaigns, and soldiers’ lives in interstellar conflict.', 1),
  (10, 'Political Space Opera', 'political-space-opera', 8, 'Empires, diplomacy, revolutions, and governance as the core engine.', 1),
  (11, 'Military SF', 'military-sf', 1, 'War stories where future tech reshapes strategy and ethics.', 1),
  (12, 'Near-Future Military SF', 'near-future-military-sf', 11, 'Feels like tomorrow’s battlefield rather than far-future empires.', 1),
  (13, 'Spec Ops SF', 'spec-ops-sf', 11, 'Small-team missions with high-tech and high-stakes objectives.', 1),
  (14, 'Cyberpunk', 'cyberpunk', 1, 'High tech + low life: megacorps, hackers, surveillance, street-level rebellion.', 1),
  (15, 'Biopunk', 'biopunk', 14, 'Genetic engineering, body modification, and biotech-driven dystopias.', 1),
  (16, 'Post-Cyberpunk', 'post-cyberpunk', 14, 'Similar tools but with more functional societies and nuanced institutions.', 1),
  (17, 'Nanopunk', 'nanopunk', 14, 'Nanotechnology as the dominant transformative (or destabilizing) force.', 1),
  (18, 'Steampunk (SF-leaning)', 'steampunk', 1, 'Retro-futurism where steam-era aesthetics power advanced contraptions.', 1),
  (19, 'Gaslamp Tech (steampunk-adjacent)', 'gaslamp-tech', 18, 'Victorian tech wonder with a moody, candlelit vibe.', 1),
  (20, 'Dieselpunk', 'dieselpunk', 1, '1920s–1940s aesthetics, industry, noir grit, and wartime tech fantasies.', 1),
  (21, 'Atompunk', 'atompunk', 1, 'Mid-century (1940s–60s) futurism, atomic age optimism, and sleek retro science.', 1),
  (22, 'Raypunk', 'raypunk', 1, 'Pulp-era rayguns, weird planets, and flamboyant retro-future designs.', 1),
  (23, 'Solarpunk', 'solarpunk', 1, 'Optimistic futures of sustainability, community, and green technology.', 1),
  (24, 'Climate Fiction (Cli-Fi)', 'climate-fiction', 1, 'Stories shaped by climate change impacts and adaptation choices.', 1),
  (25, 'Apocalyptic SF', 'apocalyptic-sf', 1, 'Civilizations collapse due to disaster, war, plague, or cosmic events.', 1),
  (26, 'Post-Apocalyptic SF', 'post-apocalyptic-sf', 25, 'Life after the fall: survival, rebuilding, and new cultures.', 1),
  (27, 'Prepper/Survival SF', 'prepper-survival-sf', 25, 'Practical survival challenges front-and-center.', 1),
  (28, 'Dystopian SF', 'dystopian-sf', 1, 'Oppressive systems where tech, ideology, or scarcity crushes freedom.', 1),
  (29, 'Surveillance State SF', 'surveillance-state-sf', 28, 'Control via data, cameras, biometrics, and predictive policing.', 1),
  (30, 'Corporate Dystopia', 'corporate-dystopia', 28, 'Society run like a company, for profit, at human cost.', 1),
  (31, 'Utopian SF', 'utopian-sf', 1, 'Imagines better societies and tests whether “better” is stable or fragile.', 1),
  (32, 'Critical Utopia', 'critical-utopia', 31, 'A hopeful system shown with cracks, compromises, and dissent.', 1),
  (33, 'First Contact SF', 'first-contact-sf', 1, 'Humanity meets aliens and must translate, negotiate, or survive.', 1),
  (34, 'Xenolinguistic SF', 'xenolinguistic-sf', 33, 'Communication and language barriers are the main battleground.', 1),
  (35, 'Alien Invasion SF', 'alien-invasion-sf', 1, 'Extraterrestrials threaten Earth, forcing resistance or adaptation.', 1),
  (36, 'Colonization/Settlement SF', 'colonization-settlement-sf', 1, 'Building new worlds and cultures on alien planets.', 1),
  (37, 'Generation Ship SF', 'generation-ship-sf', 36, 'Entire societies live and evolve aboard world-ships between stars.', 1),
  (38, 'Time Travel SF', 'time-travel-sf', 1, 'Plots revolve around causality, paradox, loops, and altered timelines.', 1),
  (39, 'Time Loop SF', 'time-loop-sf', 38, 'Repeating time frames as a puzzle, punishment, or transformation engine.', 1),
  (40, 'Alternate Timelines (time-travel)', 'alternate-timelines', 38, 'Branching histories created by interference.', 1),
  (41, 'Alternate History (SF-leaning)', 'sf-alternate-history', 1, '“What if history diverged?” explored with rigorous consequences.', 1),
  (42, 'Tech-Divergence Alt History', 'tech-divergence-alt-history', 41, 'A key invention arrives earlier or differently and reshapes the world.', 1),
  (43, 'Parallel Worlds / Multiverse SF', 'parallel-worlds-multiverse-sf', 1, 'Multiple realities collide, echo, or compete.', 1),
  (44, 'Planetary Romance', 'planetary-romance', 1, 'Exotic planets, adventure, and often a swashbuckling tone.', 1),
  (45, 'Robots/AI SF', 'robots-ai-sf', 1, 'Minds we build, what they owe us, and what we owe them.', 1),
  (46, 'AI Alignment/Ethics SF', 'ai-alignment-ethics-sf', 45, 'Control, values, and unintended consequences of artificial minds.', 1),
  (47, 'Robot Society SF', 'robot-society-sf', 45, 'Robotics as a lens on personhood, labor, and rights.', 1),
  (48, 'Transhumanist SF', 'transhumanist-sf', 1, 'Humans upgrade themselves via implants, uploads, or engineered bodies.', 1),
  (49, 'Mind Upload / Digital Immortality SF', 'mind-upload-digital-immortality-sf', 48, 'Personhood tested when minds become software.', 1),
  (50, 'Posthuman SF', 'posthuman-sf', 48, 'Futures where “human” is obsolete, modified, or replaced.', 1),
  (51, 'Singularity SF', 'singularity-sf', 1, 'Intelligence explosion radically transforms reality and comprehension.', 1),
  (52, 'Big Dumb Object (BDO) SF', 'big-dumb-object-sf', 1, 'Mysterious megastructures (rings, spheres, monoliths) drive wonder and dread.', 1),
  (53, 'Megastructure SF', 'megastructure-sf', 1, 'Dyson spheres, O’Neill cylinders, ringworlds as settings and problems.', 1),
  (54, 'Cosmic SF', 'cosmic-sf', 1, 'Deals with the vastness of the universe and humanity’s tiny place within it.', 1),
  (55, 'Cosmic Horror SF (SF-leaning)', 'cosmic-horror-sf', 54, 'Indifferent cosmos, incomprehensible entities, existential dread.', 1),
  (56, 'Space Western', 'space-western', 1, 'Frontier themes, outlaws, and sparse law in space settings.', 1),
  (57, 'Noir SF', 'noir-sf', 1, 'Crime stories with futuristic settings and morally gray investigators.', 1),
  (58, 'Medical SF', 'medical-sf', 1, 'Medicine, bioethics, pandemics, and healthcare systems in speculative contexts.', 1),
  (59, 'Eco-SF', 'eco-sf', 1, 'Ecology and planetary systems as central plot forces.', 1),
  (60, 'Frontier/Exploration SF', 'frontier-exploration-sf', 1, 'Discovery narratives: new worlds, artifacts, and unknown phenomena.', 1),
  (61, 'Satirical SF', 'satirical-sf', 1, 'Uses future tech and aliens to mock present-day absurdities.', 1),
  (62, 'Slipstream (SF-adjacent)', 'sf-slipstream', 1, 'Reality feels off-kilter without clear genre rules or explanations.', 1),
  (63, 'Science Fantasy', 'science-fantasy', NULL, 'Spacefaring settings with magic, gods, or mythic logic.', 1),
  (64, 'Techno-Fantasy', 'techno-fantasy', NULL, 'Magic presented like engineering, or technology treated as mystical.', 1),
  (65, 'Fantasy', 'fantasy', NULL, 'Speculation driven by magic, myth, the supernatural, and secondary worlds.', 1),
  (66, 'Epic Fantasy', 'epic-fantasy', 65, 'Large-scale conflicts, quests, and fate-of-the-world stakes.', 1),
  (67, 'High Fantasy', 'high-fantasy', 66, 'Entirely secondary-world settings with grand mythic scope.', 1),
  (68, 'Low Fantasy', 'low-fantasy', 66, 'Magical intrusions into a mostly nonmagical world, often Earthlike.', 1),
  (69, 'Sword & Sorcery', 'sword-sorcery', 65, 'Fast, gritty adventures with personal stakes and dangerous magic.', 1),
  (70, 'Heroic Fantasy', 'heroic-fantasy', 65, 'Larger-than-life protagonists and valor-forward storytelling.', 1),
  (71, 'Mythic Fantasy', 'mythic-fantasy', 65, 'Uses myth structures, archetypes, and sacred-feeling narratives.', 1),
  (72, 'Fairy Tale Fantasy', 'fairy-tale-fantasy', 65, 'Fairy-tale logic, motifs, and moral enchantment (often dark underneath).', 1),
  (73, 'Folklore Fantasy', 'folklore-fantasy', 65, 'Draws from regional folk beliefs, spirits, and local magic.', 1),
  (74, 'Arthurian / Chivalric Fantasy', 'arthurian-chivalric-fantasy', 65, 'Knights, quests, courts, and honor codes in mythic frames.', 1),
  (75, 'Historical Fantasy', 'historical-fantasy', 65, 'Magic woven into a real historical period.', 1),
  (76, 'Urban Fantasy', 'urban-fantasy', 65, 'Supernatural beings and magic hidden in modern cities.', 1),
  (77, 'Contemporary Fantasy', 'contemporary-fantasy', 76, 'Magic in the present day, not necessarily “city-centric.”', 1),
  (78, 'Occult Detective Fantasy', 'occult-detective-fantasy', 76, 'Investigations with demons, curses, and secret societies.', 1),
  (79, 'Dark Fantasy', 'dark-fantasy', 65, 'Horror tones inside fantasy: dread, corruption, and bleak magic.', 1),
  (80, 'Grimdark', 'grimdark', 65, 'Cynical worlds where morality is compromised and hope is expensive.', 1),
  (81, 'Romantic Fantasy', 'romantic-fantasy', 65, 'Romance is a major engine alongside magic and world stakes.', 1),
  (82, 'Romantasy', 'romantasy', 81, 'Fantasy-first settings with romance as a dominant plot pillar.', 1),
  (83, 'Fantasy of Manners', 'fantasy-of-manners', 65, 'Social rules, class, and wit drive conflict more than battles.', 1),
  (84, 'Cozy Fantasy', 'cozy-fantasy', 65, 'Warm, lower-stakes stories focused on comfort, community, and craft.', 1),
  (85, 'Comic Fantasy', 'comic-fantasy', 65, 'Humor-forward fantasy that plays with tropes and absurdity.', 1),
  (86, 'Portal Fantasy', 'portal-fantasy', 65, 'Characters travel from our world to a magical one (or vice versa).', 1),
  (87, 'Isekai', 'isekai', 86, 'A character is transported/reborn into another world with a new role.', 1),
  (88, 'Progression Fantasy', 'progression-fantasy', 65, 'Power growth is explicit and structured, often “training-to-mastery.”', 1),
  (89, 'LitRPG', 'litrpg', 88, 'Game-like stats, levels, skills, and systems appear in-world.', 1),
  (90, 'Cultivation Fantasy', 'cultivation-fantasy', 88, 'Advancement through spiritual/energy practice with staged power tiers.', 1),
  (91, 'Dungeon Core', 'dungeon-core', 88, 'A dungeon (or its spirit) is the protagonist building traps/rooms/monsters.', 1),
  (92, 'Magical Realism (fantasy-adjacent)', 'magical-realism', 65, 'The magical is treated as ordinary within an otherwise real world.', 1),
  (93, 'Mythpunk', 'mythpunk', 65, 'Punk energy applied to mythic materials: subversive, remix-heavy fantasy.', 1),
  (94, 'Gaslamp Fantasy', 'gaslamp-fantasy', 65, 'Victorian/Edwardian aesthetics with magic and occult undercurrents.', 1),
  (95, 'Steampunk Fantasy', 'steampunk-fantasy', 65, 'Steam-era style plus overt magic, not just tech extrapolation.', 1),
  (96, 'Flintlock Fantasy', 'flintlock-fantasy', 65, 'Gunpowder-era warfare with magic and empire-scale politics.', 1),
  (97, 'Wuxia (fantasy-adjacent)', 'wuxia', 65, 'Martial-arts hero tales with heightened, near-mystic skill.', 1),
  (98, 'Xianxia', 'xianxia', 65, 'Chinese-inspired immortal cultivation epics with gods, sects, and cosmic realms.', 1),
  (99, 'Mythological Retellings', 'mythological-retellings', 65, 'Familiar myths reimagined with new POVs and themes.', 1),
  (100, 'Secondary-World Fantasy', 'secondary-world-fantasy', 65, 'Invented worlds with their own history, cultures, and physics.', 1),
  (101, 'Worldbuilding-Heavy Fantasy', 'worldbuilding-heavy-fantasy', 100, 'Setting complexity is a major reader draw.', 1),
  (102, 'Elemental / Nature Fantasy', 'elemental-nature-fantasy', 65, 'Magic systems centered on elements, spirits, and natural forces.', 1),
  (103, 'Dragon / Creature-Focused Fantasy', 'dragon-creature-focused-fantasy', 65, 'Specific fantastical species drives society and plot.', 1),
  (104, 'Quest Fantasy', 'quest-fantasy', 65, 'Travel, trials, and artifact hunts are the core structure.', 1),
  (105, 'Horror', 'horror', NULL, 'Fear and dread arising from the uncanny, supernatural, or reality-breaking.', 0),
  (106, 'Supernatural Horror', 'supernatural-horror', 105, 'Ghosts, demons, curses, and the afterlife cause terror.', 1),
  (107, 'Cosmic Horror', 'cosmic-horror', 105, 'Horror from incomprehensible forces and indifferent cosmic truth.', 1),
  (108, 'Weird Horror', 'weird-horror', 105, 'Surreal, reality-warping terror that defies neat explanation.', 1),
  (109, 'Body Horror', 'body-horror', 105, 'Transformation, disease, mutation, and the fragility of flesh.', 1),
  (110, 'Folk Horror', 'folk-horror', 105, 'Rural dread, old rituals, and community secrets rooted in tradition.', 1),
  (111, 'Gothic Horror', 'gothic-horror', 105, 'Decay, obsession, haunted lineages, and atmospheric doom.', 1),
  (112, 'Haunted House Horror', 'haunted-house-horror', 105, 'Place-as-antagonist with history soaked into walls.', 1),
  (113, 'Monster Horror', 'monster-horror', 105, 'Creatures embody fears, appetites, or cultural anxieties.', 1),
  (114, 'Vampire Horror', 'vampire-horror', 113, 'Predation, desire, contagion, and immortality’s cost.', 1),
  (115, 'Werewolf Horror', 'werewolf-horror', 113, 'Rage, duality, inherited curse, and loss of control.', 1),
  (116, 'Psychological Horror (speculative-leaning)', 'psychological-horror', 105, 'Reality ambiguity and mind-based dread.', 1),
  (117, 'Techno-Horror', 'techno-horror', 105, 'Technology as the source of terror: AI, surveillance, or digital hauntings.', 1),
  (118, 'Romance', 'romance', NULL, NULL, 0),
  (119, 'Paranormal Romance', 'paranormal-romance', 118, 'Romance with vampires, shifters, witches, and supernatural factions.', 1),
  (120, 'SF Romance', 'sf-romance', 118, 'Love stories shaped by space, tech, alien cultures, or future societies.', 1),
  (121, 'Fantasy Romance', 'fantasy-romance', 118, 'Love stories in magical settings with destiny, courts, or enchantments.', 1),
  (122, 'Mystery', 'mystery', NULL, NULL, 0),
  (123, 'Science Fiction Mystery', 'science-fiction-mystery', 122, 'Cases solved with futuristic tech, alien contexts, or new laws of nature.', 1),
  (124, 'Fantasy Mystery', 'fantasy-mystery', 122, 'Whodunits with magical constraints, curses, and enchanted evidence.', 1),
  (125, 'Supernatural Thriller', 'supernatural-thriller', 160, 'High-tension plots with occult threats and uncanny stakes.', 1),
  (126, 'Time-Travel Mystery', 'time-travel-mystery', 122, 'Investigation across causality and multiple timelines.', 1),
  (127, 'Locked-Room Speculative', 'locked-room-speculative', 122, 'Constraints created by magic/tech make the puzzle possible.', 1),
  (128, 'Alternate History', 'althist-alternate-history', NULL, 'History diverges from ours and explores cascading consequences.', 1),
  (129, 'Counterfactual War History', 'counterfactual-war-history', 128, 'Different outcomes of major conflicts reshape geopolitics.', 1),
  (130, 'Cultural Divergence', 'cultural-divergence', 128, 'A social/religious/ideological shift changes the world’s development.', 1),
  (131, 'Steampunk Alternate History', 'steampunk-alternate-history', 128, 'Victorian divergence with retro tech and empire politics.', 1),
  (132, 'Dystopian / Utopian', 'dystopian-utopian', NULL, 'Speculates about social systems at their best, worst, or both.', 1),
  (133, 'Dystopia', 'dystopia', 132, 'A “bad place” revealing control, inequality, and systemic cruelty.', 1),
  (134, 'Utopia', 'utopia', 132, 'A “good place” exploring stability, ethics, and unintended tradeoffs.', 1),
  (135, 'Anti-Utopia', 'anti-utopia', 132, 'Challenges the very idea that utopia is possible without coercion.', 1),
  (136, 'Weird Fiction', 'weird-fiction', NULL, 'Stories that bend genre rules and make reality feel haunted or sideways.', 1),
  (137, 'The Weird', 'the-weird', 136, 'Uncanny events without tidy logic; awe and disgust share a table.', 1),
  (138, 'New Weird', 'new-weird', 136, 'Urban, political, and grotesque imaginings blending SF/F/H aesthetics.', 1),
  (139, 'Slipstream', 'weird-slipstream', 136, 'Literary-leaning strangeness that refuses clear speculative mechanisms.', 1),
  (140, 'Superhero Fiction (speculative branch)', 'superhero-fiction', NULL, 'Powers, vigilantes, and identity examined through extraordinary abilities.', 1),
  (141, 'Classic Superhero', 'classic-superhero', 140, 'Iconic hero/villain dynamics with moral clarity and spectacle.', 1),
  (142, 'Deconstructionist Superhero', 'deconstructionist-superhero', 140, 'Interrogates power, trauma, and social consequences.', 1),
  (143, 'Superhero Noir', 'superhero-noir', 140, 'Crime-driven plots in a powered world with moral ambiguity.', 1),
  (144, 'Speculative Adventure', 'speculative-adventure', NULL, 'Action-forward stories where the premise creates new dangers and possibilities.', 1),
  (145, 'Pulp Speculative', 'pulp-speculative', 144, 'Fast, episodic, melodramatic adventures with bold concepts.', 1),
  (146, 'Swashbuckling Fantasy', 'swashbuckling-fantasy', 144, 'Dueling, daring, and charisma in a magical world.', 1),
  (147, 'Treasure-Hunt Speculative', 'treasure-hunt-speculative', 144, 'Artifacts, ruins, and ancient tech/magic drive momentum.', 1),
  (148, 'Literary Fiction', 'literary-fiction', NULL, NULL, 0),
  (149, 'Contemporary Fiction', 'contemporary-fiction', NULL, NULL, 0),
  (150, 'Historical Fiction', 'historical-fiction', NULL, NULL, 0),
  (151, 'Crime', 'crime', NULL, NULL, 0),
  (152, 'Nonfiction', 'nonfiction', NULL, NULL, 0),
  (153, 'Biography', 'biography', NULL, NULL, 0),
  (154, 'Memoir', 'memoir', NULL, NULL, 0),
  (155, 'Essays', 'essays', NULL, NULL, 0),
  (156, 'Poetry', 'poetry', NULL, NULL, 0),
  (157, 'Drama', 'drama', NULL, NULL, 0),
  (158, 'Young Adult', 'young-adult', NULL, NULL, 0),
  (159, 'Middle Grade', 'middle-grade', NULL, NULL, 0),
  (160, 'Thriller', 'thriller', NULL, NULL, 0)
;
